version: '3.1'

services:

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always

  mariadb:
    build: requirements/mariadb
    container_name: mariadb


  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
